import requests
import pandas as pd

csv_path = r"D:\bit.pro\sample.csv"  # örnek csv yoksa aşağıdaki alternatif yöntemi kullan

# Alternatif: tek satırlık örnek veriyi doğrudan yaz
sample_data = {
    "Destination Port": 53,
    "Flow Duration": 225064,
    "Total Fwd Packets": 1,
    "Total Backward Packets": 1,
    "Total Length of Fwd Packets": 38,
    "Total Length of Bwd Packets": 119,
    "Fwd Packet Length Max": 38,
    "Fwd Packet Length Min": 38,
    "Fwd Packet Length Mean": 38.0,
    "Fwd Packet Length Std": 0.0,
    "Bwd Packet Length Max": 119,
    "Bwd Packet Length Min": 119,
    "Bwd Packet Length Mean": 119.0,
    "Bwd Packet Length Std": 0.0,
    "Flow Bytes/s": 697.5793552,
    "Flow Packets/s": 8.886361213,
    "Flow IAT Mean": 225064.0,
    "Flow IAT Std": 0.0,
    "Flow IAT Max": 225064,
    "Flow IAT Min": 225064,
    "Fwd IAT Total": 0.0,
    "Fwd IAT Mean": 0.0,
    "Fwd IAT Std": 0.0,
    "Fwd IAT Max": 0.0,
    "Fwd IAT Min": 0.0,
    "Bwd IAT Total": 0.0,
    "Bwd IAT Mean": 0.0,
    "Bwd IAT Std": 0.0,
    "Bwd IAT Max": 0.0,
    "Bwd IAT Min": 0.0,
    "Fwd PSH Flags": 0,
    "Bwd PSH Flags": 0,
    "Fwd URG Flags": 0,
    "Bwd URG Flags": 0,
    "Fwd Header Length": 0.0,
    "Bwd Header Length": 0.0,
    "Fwd Packets/s": 0.0,
    "Bwd Packets/s": 0.0,
    "Min Packet Length": 38,
    "Max Packet Length": 119,
    "Packet Length Mean": 78.5,
    "Packet Length Std": 40.5,
    "Packet Length Variance": 1640.25,
    "FIN Flag Count": 0,
    "SYN Flag Count": 0,
    "RST Flag Count": 0,
    "PSH Flag Count": 0,
    "ACK Flag Count": 0,
    "URG Flag Count": 0,
    "CWE Flag Count": 0,
    "ECE Flag Count": 0,
    "Down/Up Ratio": 1.0,
    "Average Packet Size": 78.5,
    "Avg Fwd Segment Size": 38.0,
    "Avg Bwd Segment Size": 119.0,
    "Fwd Header Length.1": 0.0,
    "Fwd Avg Bytes/Bulk": 0.0,
    "Fwd Avg Packets/Bulk": 0.0,
    "Fwd Avg Bulk Rate": 0.0,
    "Bwd Avg Bytes/Bulk": 0.0,
    "Bwd Avg Packets/Bulk": 0.0,
    "Bwd Avg Bulk Rate": 0.0,
    "Subflow Fwd Packets": 1,
    "Subflow Fwd Bytes": 38,
    "Subflow Bwd Packets": 1,
    "Subflow Bwd Bytes": 119,
    "Init_Win_bytes_forward": 0,
    "Init_Win_bytes_backward": 0,
    "act_data_pkt_fwd": 0,
    "min_seg_size_forward": 40,
    "Active Mean": 0.0,
    "Active Std": 0.0,
    "Active Max": 0.0,
    "Active Min": 0.0,
    "Idle Mean": 0.0,
    "Idle Std": 0.0,
    "Idle Max": 0.0,
    "Idle Min": 0.0
}

r = requests.post("http://127.0.0.1:5000/predict", json=sample_data)
print(r.json())